<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="activity" nsURI="http://www.polarsys.org/capella/common/activity/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.common.data.activity">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/common/activity/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractActivity" abstract="true" eSuperTypes="behavior.ecore#//AbstractBehavior modellingcore.ecore#//TraceableElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isSingleExecution" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityEdge" abstract="true" eSuperTypes="modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfRate" eType="ecore:EEnum modellingcore.ecore#//RateKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate" eType="ecore:EClass modellingcore.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" eType="ecore:EClass modellingcore.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//ActivityNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass modellingcore.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="weight" eType="ecore:EClass modellingcore.ecore#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectFlow" abstract="true" eSuperTypes="#//ActivityEdge">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMulticast" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isMultireceive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityPartition" abstract="true" eSuperTypes="modellingcore.ecore#//AbstractNamedElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDimension" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isExternal" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActivityNode" abstract="true" interface="true"
      eSuperTypes="modellingcore.ecore#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" upperBound="-1"
        eType="#//ActivityEdge"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" upperBound="-1"
        eType="#//ActivityEdge"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractAction" abstract="true" eSuperTypes="modellingcore.ecore#//AbstractNamedElement #//ActivityNode">
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputs" upperBound="-1"
        eType="#//InputPin" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputs" upperBound="-1"
        eType="#//OutputPin" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AcceptEventAction" abstract="true" eSuperTypes="#//AbstractAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isUnmarshall" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectNode" abstract="true" eSuperTypes="#//ActivityNode modellingcore.ecore#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isControlType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfNode" eType="#//ObjectNodeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordering" eType="#//ObjectNodeOrderingKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="upperBound" eType="ecore:EClass modellingcore.ecore#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inState" upperBound="-1"
        eType="ecore:EClass modellingcore.ecore#//IState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selection" eType="ecore:EClass behavior.ecore#//AbstractBehavior"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pin" abstract="true" interface="true"
      eSuperTypes="#//ObjectNode">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isControl" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputPin" abstract="true" interface="true"
      eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EClass" name="OutputPin" abstract="true" interface="true"
      eSuperTypes="#//Pin"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectNodeOrderingKind">
    <eLiterals name="FIFO"/>
    <eLiterals name="LIFO" value="1"/>
    <eLiterals name="ordered" value="2"/>
    <eLiterals name="unordered" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ObjectNodeKind">
    <eLiterals name="Unspecified"/>
    <eLiterals name="NoBuffer" value="1"/>
    <eLiterals name="Overwrite" value="2"/>
  </eClassifiers>
</ecore:EPackage>
