<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="behavior" nsURI="http://www.polarsys.org/capella/common/behavior/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.common.data.behavior">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/common/behavior/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractBehavior" abstract="true" interface="true"
      eSuperTypes="modellingcore.ecore#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isControlOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEvent" abstract="true" interface="true"
      eSuperTypes="modellingcore.ecore#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractTimeEvent" abstract="true" interface="true"
      eSuperTypes="#//AbstractEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isRelative" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
</ecore:EPackage>
