<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="capellacommon" nsURI="http://www.polarsys.org/capella/core/common/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.capellacommon">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/common/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCapabilityPkg" abstract="true"
      eSuperTypes="capellacore.ecore#//Structure"/>
  <eClassifiers xsi:type="ecore:EClass" name="GenericTrace" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//TraceableElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass modellingcore.ecore#//TraceableElement" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass modellingcore.ecore#//TraceableElement" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateMachine" eSuperTypes="capellacore.ecore#//CapellaElement behavior.ecore#//AbstractBehavior">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRegions" upperBound="-1"
        eType="#//Region" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Region" eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStates" upperBound="-1"
        eType="#//AbstractState" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedTransitions" upperBound="-1"
        eType="#//StateTransition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedStates" upperBound="-1"
        eType="#//AbstractState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="State" eSuperTypes="#//AbstractState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRegions" upperBound="-1"
        eType="#//Region" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableAbstractFunctions"
        upperBound="-1" eType="ecore:EClass fa.ecore#//AbstractFunction" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableFunctionalChains"
        upperBound="-1" eType="ecore:EClass fa.ecore#//FunctionalChain" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableAbstractCapabilities"
        upperBound="-1" eType="ecore:EClass interaction.ecore#//AbstractCapability"
        resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="doActivity" eType="ecore:EClass behavior.ecore#//AbstractEvent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mode" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="FinalState" eSuperTypes="#//State"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractState" abstract="true" eSuperTypes="capellacore.ecore#//NamedElement modellingcore.ecore#//IState">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedAbstractStates"
        upperBound="-1" eType="#//AbstractState" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StateTransition" eSuperTypes="capellacore.ecore#//NamedElement capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//TransitionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="triggerDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass capellacore.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="#//AbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="#//AbstractState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="effect" eType="ecore:EClass behavior.ecore#//AbstractEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggers" upperBound="-1"
        eType="ecore:EClass behavior.ecore#//AbstractEvent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedStateTransitions"
        upperBound="-1" eType="#//StateTransition" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Pseudostate" abstract="true" eSuperTypes="#//AbstractState"/>
  <eClassifiers xsi:type="ecore:EClass" name="InitialPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="JoinPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="ForkPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="ChoicePseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="TerminatePseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="ShallowHistoryPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeepHistoryPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="EntryPointPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExitPointPseudoState" eSuperTypes="#//Pseudostate"/>
  <eClassifiers xsi:type="ecore:EClass" name="StateEvent" abstract="true" eSuperTypes="capellacore.ecore#//NamedElement behavior.ecore#//AbstractEvent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="condition" eType="ecore:EClass capellacore.ecore#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ChangeEvent" eSuperTypes="#//StateEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ChangeEventKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeEvent" eSuperTypes="#//StateEvent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//TimeEventKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransitionKind">
    <eLiterals name="internal"/>
    <eLiterals name="local" value="1"/>
    <eLiterals name="external" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeEventKind">
    <eLiterals name="AT"/>
    <eLiterals name="AFTER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeEventKind">
    <eLiterals name="WHEN"/>
  </eClassifiers>
</ecore:EPackage>
