<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="capellamodeller" nsURI="http://www.polarsys.org/capella/core/modeller/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.capellamodeller">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/modeller/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyValuePairs" upperBound="-1"
        eType="ecore:EClass capellacore.ecore#//KeyValue" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedModelRoots" upperBound="-1"
        eType="#//ModelRoot" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ModelRoot" abstract="true" interface="true"
      eSuperTypes="capellacore.ecore#//CapellaElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemEngineering" eSuperTypes="#//ModelRoot capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedOperationalAnalysis"
        upperBound="-1" eType="ecore:EClass oa.ecore#//OperationalAnalysis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedSystemAnalysis"
        upperBound="-1" eType="ecore:EClass ctx.ecore#//SystemAnalysis" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedLogicalArchitectures"
        upperBound="-1" eType="ecore:EClass la.ecore#//LogicalArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPhysicalArchitectures"
        upperBound="-1" eType="ecore:EClass pa.ecore#//PhysicalArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedEPBSArchitectures"
        upperBound="-1" eType="ecore:EClass epbs.ecore#//EPBSArchitecture" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedSharedPkgs" upperBound="-1"
        eType="ecore:EClass sharedmodel.ecore#//SharedPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Library" eSuperTypes="#//Project"/>
</ecore:EPackage>
