<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="cs" nsURI="http://www.polarsys.org/capella/core/cs/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.cs">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/cs/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="BlockArchitecture" abstract="true" eSuperTypes="fa.ecore#//AbstractFunctionalArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRequirementPkgs" upperBound="-1"
        eType="ecore:EClass requirement.ecore#//RequirementsPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInterfacePkg" eType="#//InterfacePkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDataPkg" eType="ecore:EClass information.ecore#//DataPkg"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" abstract="true" eSuperTypes="fa.ecore#//AbstractFunctionalBlock capellacore.ecore#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAbstractCapabilityPkg"
        eType="ecore:EClass capellacommon.ecore#//AbstractCapabilityPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInterfacePkg" eType="#//InterfacePkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDataPkg" eType="ecore:EClass information.ecore#//DataPkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStateMachines" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//StateMachine" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Component" abstract="true" eSuperTypes="#//Block information.ecore#//PartitionableElement information.ecore#//communication/CommunicationLinkExchanger capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="usedInterfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="implementedInterfaces"
        upperBound="-1" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedComponents" upperBound="-1"
        eType="#//Component"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
        eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedComponentPorts"
        upperBound="-1" eType="ecore:EClass fa.ecore#//ComponentPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedParts" upperBound="-1"
        eType="#//Part" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPhysicalPorts"
        upperBound="-1" eType="#//PhysicalPort" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalPath" upperBound="-1"
        eType="#//PhysicalPath" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalLinks" upperBound="-1"
        eType="#//PhysicalLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalLinkCategories"
        upperBound="-1" eType="#//PhysicalLinkCategory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractActor" abstract="true" eSuperTypes="#//Component capellacore.ecore#//InvolvedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="Part" eSuperTypes="information.ecore#//Partition modellingcore.ecore#//InformationsExchanger #//DeployableElement #//DeploymentTarget #//AbstractPathInvolvedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedParts" upperBound="-1"
        eType="#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAbstractType" eType="ecore:EClass modellingcore.ecore#//AbstractType"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemComponent" abstract="true" eSuperTypes="#//Component capellacore.ecore#//InvolvedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dataComponent" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InterfacePkg" eSuperTypes="information.ecore#//communication/MessageReferencePkg capellacore.ecore#//AbstractExchangeItemPkg capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInterfaces" upperBound="-1"
        eType="#//Interface" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInterfacePkgs" upperBound="-1"
        eType="#//InterfacePkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Interface" eSuperTypes="capellacore.ecore#//GeneralClass capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mechanism" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExchangeItemAllocations"
        upperBound="-1" eType="#//ExchangeItemAllocation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedContextInterfaces"
        upperBound="-1" eType="#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedLogicalInterfaces"
        upperBound="-1" eType="#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeItemAllocation" eSuperTypes="information.ecore#//AbstractEventOperation capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendProtocol" eType="ecore:EEnum information.ecore#//communication/CommunicationLinkProtocol"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiveProtocol" eType="ecore:EEnum information.ecore#//communication/CommunicationLinkProtocol"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedItem" eType="ecore:EClass information.ecore#//ExchangeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeployableElement" abstract="true" eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="DeploymentTarget" abstract="true" eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractDeploymentLink" abstract="true"
      eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedElement" lowerBound="1"
        eType="#//DeployableElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="location" lowerBound="1"
        eType="#//DeploymentTarget"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPathInvolvedElement" abstract="true"
      eSuperTypes="capellacore.ecore#//InvolvedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalArtifact" abstract="true"
      eSuperTypes="capellacore.ecore#//CapellaElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalLinkEnd" abstract="true"
      eSuperTypes="capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedLinks" upperBound="-1"
        eType="#//PhysicalLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalLink" eSuperTypes="#//AbstractPhysicalArtifact #//AbstractPathInvolvedElement fa.ecore#//ComponentExchangeAllocator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkEnds" lowerBound="2"
        upperBound="2" eType="#//AbstractPhysicalLinkEnd"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalLinkEnds"
        upperBound="-1" eType="#//PhysicalLinkEnd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//PhysicalLinkCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePhysicalPort" eType="#//PhysicalPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPhysicalPort" eType="#//PhysicalPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedPhysicalLinks"
        upperBound="-1" eType="#//PhysicalLink"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalLinkCategory" eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalLinkEnd" eSuperTypes="#//AbstractPhysicalLinkEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="#//PhysicalPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" eType="#//Part"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalPath" eSuperTypes="capellacore.ecore#//NamedElement fa.ecore#//ComponentExchangeAllocator #//AbstractPathInvolvedElement capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalPathInvolvements"
        upperBound="-1" eType="#//PhysicalPathInvolvement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstPhysicalPathInvolvements"
        upperBound="-1" eType="#//PhysicalPathInvolvement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedPhysicalPaths"
        upperBound="-1" eType="#//PhysicalPath"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalPathInvolvement" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextInvolvements" upperBound="-1"
        eType="#//PhysicalPathInvolvement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedElement" eType="#//AbstractPathInvolvedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalPathReference" eSuperTypes="#//PhysicalPathInvolvement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedPhysicalPath"
        eType="#//PhysicalPath"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalPort" eSuperTypes="information.ecore#//Partition information.ecore#//Port #//AbstractPhysicalArtifact modellingcore.ecore#//InformationsExchanger #//AbstractPhysicalLinkEnd">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedComponentPorts"
        upperBound="-1" eType="ecore:EClass fa.ecore#//ComponentPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedPhysicalPorts"
        upperBound="-1" eType="#//PhysicalPort"/>
  </eClassifiers>
</ecore:EPackage>
