<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ctx" nsURI="http://www.polarsys.org/capella/core/ctx/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.ctx">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/ctx/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SystemAnalysis" eSuperTypes="cs.ecore#//BlockArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSystemContext" eType="#//SystemContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSystem" lowerBound="1"
        eType="#//System" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActorPkg" eType="#//ActorPkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMissionPkg" eType="#//MissionPkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedCapabilityPkg"
        eType="#//CapabilityPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedSystemFunctionPkg"
        eType="#//SystemFunctionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedOperationalAnalyses"
        upperBound="-1" eType="ecore:EClass oa.ecore#//OperationalAnalysis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="System" eSuperTypes="cs.ecore#//Component capellacore.ecore#//InvolvedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedSystemFunctions"
        upperBound="-1" eType="#//SystemFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedEntities" upperBound="-1"
        eType="ecore:EClass oa.ecore#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemFunction" eSuperTypes="fa.ecore#//AbstractFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSystemFunctionPkgs"
        upperBound="-1" eType="#//SystemFunctionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedOperationalActivities"
        upperBound="-1" eType="ecore:EClass oa.ecore#//OperationalActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedSystemFunctions"
        upperBound="-1" eType="#//SystemFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemFunctionPkg" eSuperTypes="fa.ecore#//FunctionPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSystemFunctions" upperBound="-1"
        eType="#//SystemFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSystemFunctionPkgs"
        upperBound="-1" eType="#//SystemFunctionPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Actor" eSuperTypes="cs.ecore#//AbstractActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedSystemFunctions"
        upperBound="-1" eType="#//SystemFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedEntities" upperBound="-1"
        eType="ecore:EClass oa.ecore#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedOperationalActors"
        upperBound="-1" eType="ecore:EClass oa.ecore#//OperationalActor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActorPkg" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActors" upperBound="-1"
        eType="#//Actor" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedActorPkgs" upperBound="-1"
        eType="#//ActorPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mission" eSuperTypes="capellacore.ecore#//NamedElement capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingActors" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingSystem" eType="#//System"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exploitedCapabilities"
        upperBound="-1" eType="#//Capability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MissionPkg" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMissionPkgs" upperBound="-1"
        eType="#//MissionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMissions" upperBound="-1"
        eType="#//Mission" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Capability" eSuperTypes="interaction.ecore#//AbstractCapability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingActors" upperBound="-1"
        eType="#//Actor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingSystem" eType="#//System"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedOperationalCapabilities"
        upperBound="-1" eType="ecore:EClass oa.ecore#//OperationalCapability"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityPkg" eSuperTypes="capellacommon.ecore#//AbstractCapabilityPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCapabilities" upperBound="-1"
        eType="#//Capability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCapabilityPkgs" upperBound="-1"
        eType="#//CapabilityPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemContext" eSuperTypes="cs.ecore#//Component"/>
</ecore:EPackage>
