<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="epbs" nsURI="http://www.polarsys.org/capella/core/epbs/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.epbs">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/epbs/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="EPBSArchitecture" eSuperTypes="cs.ecore#//BlockArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEPBSContext" eType="#//EPBSContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItem"
        eType="#//ConfigurationItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItemPkg"
        eType="#//ConfigurationItemPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedCapabilityRealizationPkg"
        eType="ecore:EClass la.ecore#//CapabilityRealizationPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalArchitectures"
        upperBound="-1" eType="ecore:EClass pa.ecore#//PhysicalArchitecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EPBSContext" eSuperTypes="cs.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationItemPkg" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItems"
        upperBound="-1" eType="#//ConfigurationItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItemPkgs"
        upperBound="-1" eType="#//ConfigurationItemPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigurationItem" eSuperTypes="cs.ecore#//SystemComponent">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemIdentifier" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ConfigurationItemKind"
        defaultValueLiteral="Unset"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItems"
        upperBound="-1" eType="#//ConfigurationItem" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurationItemPkgs"
        upperBound="-1" eType="#//ConfigurationItemPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalArtifacts"
        ordered="false" upperBound="-1" eType="ecore:EClass cs.ecore#//AbstractPhysicalArtifact"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConfigurationItemKind">
    <eLiterals name="Unset"/>
    <eLiterals name="COTSCI" value="1"/>
    <eLiterals name="CSCI" value="2"/>
    <eLiterals name="HWCI" value="3"/>
    <eLiterals name="InterfaceCI" value="4"/>
    <eLiterals name="NDICI" value="5"/>
    <eLiterals name="PrimeItemCI" value="6"/>
    <eLiterals name="SystemCI" value="7"/>
  </eClassifiers>
</ecore:EPackage>
