<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="fa" nsURI="http://www.polarsys.org/capella/core/fa/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.fa">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/fa/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFunctionalArchitecture" abstract="true"
      eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchanges"
        upperBound="-1" eType="#//ComponentExchange" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchangeCategories"
        upperBound="-1" eType="#//ComponentExchangeCategory" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFunctionalStructure" abstract="true"
      eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchanges"
        upperBound="-1" eType="#//ComponentExchange" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchangeCategories"
        upperBound="-1" eType="#//ComponentExchangeCategory" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFunctionalBlock" abstract="true"
      eSuperTypes="capellacore.ecore#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchanges"
        upperBound="-1" eType="#//ComponentExchange" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchangeCategories"
        upperBound="-1" eType="#//ComponentExchangeCategory" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionPkg" abstract="true" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCategories" upperBound="-1"
        eType="#//ExchangeCategory" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeCategory" eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalChain" eSuperTypes="capellacore.ecore#//NamedElement capellacore.ecore#//InvolvedElement capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//FunctionalChainKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFunctionalChainInvolvements"
        upperBound="-1" eType="#//FunctionalChainInvolvement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableInStates" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstFunctionalChainInvolvements"
        upperBound="-1" eType="#//FunctionalChainInvolvement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedFunctionalChains"
        upperBound="-1" eType="#//FunctionalChain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFunctionalChainContainer" abstract="true"
      eSuperTypes="capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFunctionalChains"
        upperBound="-1" eType="#//FunctionalChain" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalChainInvolvement" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextFunctionalChainInvolvements"
        upperBound="-1" eType="#//FunctionalChainInvolvement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedElement" eType="ecore:EClass capellacore.ecore#//InvolvedElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalChainReference" eSuperTypes="#//FunctionalChainInvolvement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedFunctionalChain"
        eType="#//FunctionalChain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionInputPort" eSuperTypes="#//FunctionPort activity.ecore#//InputPin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingExchangeItems"
        upperBound="-1" eType="ecore:EClass information.ecore#//ExchangeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionOutputPort" eSuperTypes="#//FunctionPort activity.ecore#//OutputPin">
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingExchangeItems"
        upperBound="-1" eType="ecore:EClass information.ecore#//ExchangeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionalExchange" eSuperTypes="capellacore.ecore#//NamedElement capellacore.ecore#//InvolvedElement activity.ecore#//ObjectFlow behavior.ecore#//AbstractEvent information.ecore#//AbstractEventOperation capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangedItems" upperBound="-1"
        eType="ecore:EClass information.ecore#//ExchangeItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//ExchangeCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceFunctionOutputPort"
        eType="#//FunctionOutputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetFunctionInputPort"
        eType="#//FunctionInputPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedFunctionalExchanges"
        upperBound="-1" eType="#//FunctionalExchange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractFunction" abstract="true" eSuperTypes="capellacore.ecore#//Namespace capellacore.ecore#//InvolvedElement #//AbstractFunctionalChainContainer behavior.ecore#//AbstractEvent information.ecore#//Property activity.ecore#//AbstractAction">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//FunctionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="condition" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedFunctionalExchanges"
        upperBound="-1" eType="#//FunctionalExchange" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableInStates" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="linkedStateMachine" eType="ecore:EClass capellacommon.ecore#//StateMachine"
        resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FunctionPort" abstract="true" eSuperTypes="information.ecore#//Port capellacore.ecore#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedFunctionPorts"
        upperBound="-1" eType="#//FunctionPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentExchange" eSuperTypes="behavior.ecore#//AbstractEvent information.ecore#//AbstractEventOperation capellacore.ecore#//NamedElement modellingcore.ecore#//AbstractInformationFlow">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ComponentExchangeKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="oriented" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedFunctionalExchanges"
        upperBound="-1" eType="#//FunctionalExchange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponentExchangeEnds"
        upperBound="-1" eType="#//ComponentExchangeEnd" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePort" eType="ecore:EClass information.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourcePart" eType="ecore:EClass cs.ecore#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" eType="ecore:EClass information.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPart" eType="ecore:EClass cs.ecore#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="categories" upperBound="-1"
        eType="#//ComponentExchangeCategory"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedComponentExchanges"
        upperBound="-1" eType="#//ComponentExchange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentExchangeAllocator" abstract="true"
      eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedComponentExchanges"
        upperBound="-1" eType="#//ComponentExchange"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentExchangeCategory" eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentExchangeEnd" eSuperTypes="modellingcore.ecore#//InformationsExchanger capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="port" eType="ecore:EClass information.ecore#//Port"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="part" eType="ecore:EClass information.ecore#//Partition"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ComponentPort" eSuperTypes="information.ecore#//Port information.ecore#//Partition modellingcore.ecore#//InformationsExchanger">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="orientation" eType="#//OrientationPortKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ComponentPortKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="componentExchanges" upperBound="-1"
        eType="#//ComponentExchange"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedFunctionPorts"
        upperBound="-1" eType="#//FunctionPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="delegatedComponentPorts"
        upperBound="-1" eType="#//ComponentPort"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedComponentPorts"
        upperBound="-1" eType="#//ComponentPort"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FunctionalChainKind">
    <eLiterals name="SIMPLE"/>
    <eLiterals name="COMPOSITE" value="1"/>
    <eLiterals name="FRAGMENT" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="FunctionKind">
    <eLiterals name="FUNCTION"/>
    <eLiterals name="DUPLICATE" value="1"/>
    <eLiterals name="GATHER" value="2"/>
    <eLiterals name="SELECT" value="3"/>
    <eLiterals name="SPLIT" value="4"/>
    <eLiterals name="ROUTE" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentExchangeKind">
    <eLiterals name="UNSET"/>
    <eLiterals name="DELEGATION" value="1"/>
    <eLiterals name="ASSEMBLY" value="2"/>
    <eLiterals name="FLOW" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ComponentPortKind">
    <eLiterals name="STANDARD"/>
    <eLiterals name="FLOW" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="OrientationPortKind">
    <eLiterals name="UNSET"/>
    <eLiterals name="IN" value="1"/>
    <eLiterals name="OUT" value="2"/>
    <eLiterals name="INOUT" value="3"/>
  </eClassifiers>
</ecore:EPackage>
