<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="information" nsURI="http://www.polarsys.org/capella/core/information/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.information">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/information/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="AssociationPkg" abstract="true" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EEnum capellacore.ecore#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAssociations" upperBound="-1"
        eType="#//Association" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Association" eSuperTypes="capellacore.ecore#//NamedElement capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMembers" upperBound="2"
        eType="#//Property" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="navigableMembers" upperBound="2"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Class" eSuperTypes="capellacore.ecore#//GeneralClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="keyParts" upperBound="-1"
        eType="#//KeyPart"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStateMachines" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//StateMachine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDataValues" upperBound="-1"
        eType="#//datavalue/DataValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedClasses" upperBound="-1"
        eType="#//Class"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" eSuperTypes="capellacore.ecore#//Classifier #//MultiplicityElement #//datavalue/DataValueContainer modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPrimitive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EEnum capellacore.ecore#//VisibilityKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//CollectionKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregationKind" eType="#//AggregationKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass capellacore.ecore#//Type"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" unique="false" upperBound="-1"
        eType="#//datatype/DataType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedOperations" upperBound="-1"
        eType="#//Operation" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCollectionValue" abstract="true"
      eSuperTypes="#//datavalue/DataValue"/>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionValue" eSuperTypes="#//AbstractCollectionValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1"
        eType="#//datavalue/DataValue" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefaultElement" eType="#//datavalue/DataValue"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CollectionValueReference" eSuperTypes="#//AbstractCollectionValue">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//AbstractCollectionValue"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataPkg" eSuperTypes="capellacore.ecore#//AbstractExchangeItemPkg #//AssociationPkg #//datavalue/DataValueContainer #//communication/MessageReferencePkg capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDataPkgs" upperBound="-1"
        eType="#//DataPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedClasses" upperBound="-1"
        eType="#//Class" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedKeyParts" upperBound="-1"
        eType="#//KeyPart" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCollections" upperBound="-1"
        eType="#//Collection" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedUnits" upperBound="-1"
        eType="#//Unit" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDataTypes" upperBound="-1"
        eType="#//datatype/DataType" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSignals" upperBound="-1"
        eType="#//communication/Signal" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMessages" upperBound="-1"
        eType="#//communication/Message" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExceptions" upperBound="-1"
        eType="#//communication/Exception" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStateEvents" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//StateEvent" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DomainElement" eSuperTypes="#//Class"/>
  <eClassifiers xsi:type="ecore:EClass" name="KeyPart" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="property" lowerBound="1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultiplicityElement" abstract="true"
      eSuperTypes="capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ordered" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unique" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minInclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxInclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefaultValue" eType="#//datavalue/DataValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMinValue" eType="#//datavalue/DataValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMaxValue" eType="#//datavalue/DataValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNullValue" eType="#//datavalue/DataValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMinCard" eType="#//datavalue/NumericValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMinLength" eType="#//datavalue/NumericValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMaxCard" eType="#//datavalue/NumericValue"
        containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMaxLength" eType="#//datavalue/NumericValue"
        containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Operation" abstract="true" eSuperTypes="capellacore.ecore#//Feature behavior.ecore#//AbstractEvent #//AbstractEventOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParameters" upperBound="-1"
        eType="#//Parameter" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedOperations" upperBound="-1"
        eType="#//Operation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedExchangeItems"
        upperBound="-1" eType="#//ExchangeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Parameter" eSuperTypes="capellacore.ecore#//TypedElement #//MultiplicityElement modellingcore.ecore#//AbstractParameter">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//ParameterDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="passingMode" eType="#//PassingMode"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="capellacore.ecore#//Feature capellacore.ecore#//TypedElement #//MultiplicityElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="aggregationKind" eType="#//AggregationKind"
        defaultValueLiteral="UNSET"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isDerived" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isReadOnly" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isPartOfKey" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Service" eSuperTypes="#//Operation">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="synchronismKind" eType="#//SynchronismKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="thrownExceptions" upperBound="-1"
        eType="#//communication/Exception"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Union" eSuperTypes="#//Class">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//UnionKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discriminant" eType="#//UnionProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultProperty" eType="#//UnionProperty"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedUnionProperties"
        upperBound="-1" eType="#//UnionProperty" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnionProperty" eSuperTypes="#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="qualifier" upperBound="-1"
        eType="#//datavalue/DataValue"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Unit" eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="PartitionableElement" abstract="true"
      eSuperTypes="capellacore.ecore#//Classifier"/>
  <eClassifiers xsi:type="ecore:EClass" name="Partition" abstract="true" interface="true"
      eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="Port" abstract="true" eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedProtocols" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//StateMachine" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="providedInterfaces" upperBound="-1"
        eType="ecore:EClass cs.ecore#//Interface"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="requiredInterfaces" upperBound="-1"
        eType="ecore:EClass cs.ecore#//Interface"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeItem" eSuperTypes="modellingcore.ecore#//AbstractExchangeItem behavior.ecore#//AbstractEvent capellacore.ecore#//GeneralizableElement modellingcore.ecore#//AbstractType modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="exchangeMechanism" lowerBound="1"
        eType="#//ExchangeMechanism"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedElements" upperBound="-1"
        eType="#//ExchangeItemElement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedExchangeItemInstances"
        upperBound="-1" eType="#//ExchangeItemInstance" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedExchangeItems"
        upperBound="-1" eType="#//ExchangeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeItemElement" eSuperTypes="capellacore.ecore#//NamedElement #//MultiplicityElement capellacore.ecore#//TypedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ElementKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="direction" eType="#//ParameterDirection"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="composite" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperties" upperBound="-1"
        eType="#//Property"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExchangeItemInstance" eSuperTypes="#//Property"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractEventOperation" abstract="true"
      eSuperTypes="capellacore.ecore#//NamedElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="AggregationKind">
    <eLiterals name="UNSET"/>
    <eLiterals name="ASSOCIATION" value="1"/>
    <eLiterals name="AGGREGATION" value="2"/>
    <eLiterals name="COMPOSITION" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterDirection">
    <eLiterals name="IN"/>
    <eLiterals name="OUT" value="1"/>
    <eLiterals name="INOUT" value="2"/>
    <eLiterals name="RETURN" value="3"/>
    <eLiterals name="EXCEPTION" value="4"/>
    <eLiterals name="UNSET" value="5"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PassingMode">
    <eLiterals name="UNSET"/>
    <eLiterals name="BY_REF" value="1"/>
    <eLiterals name="BY_VALUE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="SynchronismKind">
    <eLiterals name="UNSET"/>
    <eLiterals name="SYNCHRONOUS" value="1"/>
    <eLiterals name="ASYNCHRONOUS" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="UnionKind">
    <eLiterals name="UNION"/>
    <eLiterals name="VARIANT" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ExchangeMechanism">
    <eLiterals name="UNSET"/>
    <eLiterals name="FLOW" value="1"/>
    <eLiterals name="OPERATION" value="2"/>
    <eLiterals name="EVENT" value="3"/>
    <eLiterals name="SHARED_DATA" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ElementKind">
    <eLiterals name="TYPE"/>
    <eLiterals name="MEMBER" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="CollectionKind">
    <eLiterals name="ARRAY"/>
    <eLiterals name="SEQUENCE" value="1"/>
  </eClassifiers>
  <eSubpackages name="communication" nsURI="http://www.polarsys.org/capella/core/information/communication/0.8.0/semantic"
      nsPrefix="org.polarsys.capella.core.data.information.communication">
    <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
      <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/information/communication/0.8.0"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationItem" abstract="true"
        eSuperTypes="capellacore.ecore#//Classifier #//datavalue/DataValueContainer">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EEnum capellacore.ecore#//VisibilityKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedStateMachines" upperBound="-1"
          eType="ecore:EClass capellacommon.ecore#//StateMachine" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Exception" eSuperTypes="#//communication/CommunicationItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="Message" eSuperTypes="#//communication/CommunicationItem"/>
    <eClassifiers xsi:type="ecore:EClass" name="MessageReference" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="message" lowerBound="1"
          eType="#//communication/Message"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="MessageReferencePkg" abstract="true"
        eSuperTypes="capellacore.ecore#//Structure">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMessageReferences"
          upperBound="-1" eType="#//communication/MessageReference" containment="true"
          resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Signal" eSuperTypes="#//communication/CommunicationItem modellingcore.ecore#//AbstractType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="signalInstances" upperBound="-1"
          eType="#//communication/SignalInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="SignalInstance" eSuperTypes="#//Property"/>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationLink" eSuperTypes="capellacore.ecore#//CapellaElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//communication/CommunicationLinkKind"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="protocol" eType="#//communication/CommunicationLinkProtocol"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="exchangeItem" eType="#//ExchangeItem"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="CommunicationLinkExchanger" abstract="true">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCommunicationLinks"
          upperBound="-1" eType="#//communication/CommunicationLink" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CommunicationLinkKind">
      <eLiterals name="UNSET"/>
      <eLiterals name="PRODUCE" value="1"/>
      <eLiterals name="CONSUME" value="2"/>
      <eLiterals name="SEND" value="3"/>
      <eLiterals name="RECEIVE" value="4"/>
      <eLiterals name="CALL" value="5"/>
      <eLiterals name="EXECUTE" value="6"/>
      <eLiterals name="WRITE" value="7"/>
      <eLiterals name="ACCESS" value="8"/>
      <eLiterals name="ACQUIRE" value="9"/>
      <eLiterals name="TRANSMIT" value="10"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="CommunicationLinkProtocol">
      <eLiterals name="UNSET"/>
      <eLiterals name="UNICAST" value="1"/>
      <eLiterals name="MULTICAST" value="2"/>
      <eLiterals name="BROADCAST" value="3"/>
      <eLiterals name="SYNCHRONOUS" value="4"/>
      <eLiterals name="ASYNCHRONOUS" value="5"/>
      <eLiterals name="READ" value="6"/>
      <eLiterals name="ACCEPT" value="7"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="datatype" nsURI="http://www.polarsys.org/capella/core/information/datatype/0.8.0/semantic"
      nsPrefix="org.polarsys.capella.core.data.information.datatype">
    <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
      <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/information/datatype/0.8.0"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataType" abstract="true" eSuperTypes="capellacore.ecore#//GeneralizableElement #//datavalue/DataValueContainer modellingcore.ecore#//ModelElement">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="discrete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="minInclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxInclusive" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
          defaultValueLiteral="true"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="visibility" eType="ecore:EEnum capellacore.ecore#//VisibilityKind"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="defaultValue" eType="#//datavalue/DataValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nullValue" eType="#//datavalue/DataValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="realizedDataTypes" upperBound="-1"
          eType="#//datatype/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanType" eSuperTypes="#//datatype/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiterals" upperBound="2"
          eType="#//datavalue/LiteralBooleanValue" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefaultValue" eType="#//datavalue/AbstractBooleanValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Enumeration" eSuperTypes="#//datatype/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLiterals" upperBound="-1"
          eType="#//datavalue/EnumerationLiteral" containment="true" resolveProxies="false"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefaultValue" eType="#//datavalue/AbstractEnumerationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNullValue" eType="#//datavalue/AbstractEnumerationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMinValue" eType="#//datavalue/AbstractEnumerationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMaxValue" eType="#//datavalue/AbstractEnumerationValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainType" eType="#//datatype/DataType"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringType" eSuperTypes="#//datatype/DataType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefaultValue" eType="#//datavalue/AbstractStringValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNullValue" eType="#//datavalue/AbstractStringValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMinLength" eType="#//datavalue/NumericValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMaxLength" eType="#//datavalue/NumericValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumericType" eSuperTypes="#//datatype/DataType">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//datatype/NumericTypeKind"
          defaultValueLiteral="INTEGER"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDefaultValue" eType="#//datavalue/NumericValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedNullValue" eType="#//datavalue/NumericValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMinValue" eType="#//datavalue/NumericValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMaxValue" eType="#//datavalue/NumericValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PhysicalQuantity" eSuperTypes="#//datatype/NumericType">
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//Unit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="NumericTypeKind">
      <eLiterals name="INTEGER"/>
      <eLiterals name="FLOAT" value="1"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="datavalue" nsURI="http://www.polarsys.org/capella/core/information/datavalue/0.8.0/semantic"
      nsPrefix="org.polarsys.capella.core.data.information.datavalue">
    <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
      <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/information/datavalue/0.8.0"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="DataValue" abstract="true" eSuperTypes="capellacore.ecore#//NamedElement modellingcore.ecore#//ValueSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="abstract" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass capellacore.ecore#//Type"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DataValueContainer" abstract="true"
        eSuperTypes="capellacore.ecore#//Structure">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDataValues" upperBound="-1"
          eType="#//datavalue/DataValue" containment="true" resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractBooleanValue" abstract="true"
        eSuperTypes="#//datavalue/DataValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralBooleanValue" eSuperTypes="#//datavalue/AbstractBooleanValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BooleanReference" eSuperTypes="#//datavalue/AbstractBooleanValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//datavalue/AbstractBooleanValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractEnumerationValue" abstract="true"
        eSuperTypes="#//datavalue/DataValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationLiteral" eSuperTypes="#//datavalue/AbstractEnumerationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="domainValue" eType="#//datavalue/DataValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="EnumerationReference" eSuperTypes="#//datavalue/AbstractEnumerationValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//datavalue/AbstractEnumerationValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractStringValue" abstract="true"
        eSuperTypes="#//datavalue/DataValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralStringValue" eSuperTypes="#//datavalue/AbstractStringValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="StringReference" eSuperTypes="#//datavalue/AbstractStringValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//datavalue/AbstractStringValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumericValue" abstract="true" eSuperTypes="#//datavalue/DataValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="unit" eType="#//Unit"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="LiteralNumericValue" eSuperTypes="#//datavalue/NumericValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NumericReference" eSuperTypes="#//datavalue/NumericValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//datavalue/NumericValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractComplexValue" abstract="true"
        eSuperTypes="#//datavalue/DataValue"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexValue" eSuperTypes="#//datavalue/AbstractComplexValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedParts" upperBound="-1"
          eType="#//datavalue/ValuePart" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ComplexValueReference" eSuperTypes="#//datavalue/AbstractComplexValue">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedValue" eType="#//datavalue/AbstractComplexValue"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ValuePart" eSuperTypes="capellacore.ecore#//CapellaElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="referencedProperty" eType="#//Property"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedValue" eType="#//datavalue/DataValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractExpressionValue" abstract="true"
        eSuperTypes="#//datavalue/AbstractBooleanValue #//datavalue/AbstractComplexValue #//datavalue/AbstractEnumerationValue #//datavalue/NumericValue #//datavalue/AbstractStringValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="expression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="unparsedExpression" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="BinaryExpression" eSuperTypes="#//datavalue/AbstractExpressionValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//datavalue/BinaryOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLeftOperand" eType="#//datavalue/DataValue"
          containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRightOperand" eType="#//datavalue/DataValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="UnaryExpression" eSuperTypes="#//datavalue/AbstractExpressionValue">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//datavalue/UnaryOperator"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperand" eType="#//datavalue/DataValue"
          containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="OpaqueExpression" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//ValueSpecification">
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="bodies" unique="false"
          upperBound="-1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="languages" upperBound="-1"
          eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="BinaryOperator">
      <eLiterals name="UNSET"/>
      <eLiterals name="ADD" value="1"/>
      <eLiterals name="MUL" value="2"/>
      <eLiterals name="SUB" value="3"/>
      <eLiterals name="DIV" value="4"/>
      <eLiterals name="POW" value="5"/>
      <eLiterals name="MIN" value="6"/>
      <eLiterals name="MAX" value="7"/>
      <eLiterals name="EQU" value="8"/>
      <eLiterals name="IOR" value="9"/>
      <eLiterals name="XOR" value="10"/>
      <eLiterals name="AND" value="11"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="UnaryOperator">
      <eLiterals name="UNSET"/>
      <eLiterals name="NOT" value="1"/>
      <eLiterals name="POS" value="2"/>
      <eLiterals name="VAL" value="3"/>
      <eLiterals name="SUC" value="4"/>
      <eLiterals name="PRE" value="5"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
