<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="interaction" nsURI="http://www.polarsys.org/capella/core/interaction/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.interaction">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/interaction/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceMessage" eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//MessageKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangeContext" eType="ecore:EClass capellacore.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="invokedOperation" eType="ecore:EClass information.ecore#//AbstractEventOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangedItems" upperBound="-1"
        eType="ecore:EClass information.ecore#//ExchangeItem"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendingPart" eType="ecore:EClass cs.ecore#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivingPart" eType="ecore:EClass cs.ecore#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sendingFunction" eType="ecore:EClass fa.ecore#//AbstractFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="receivingFunction" eType="ecore:EClass fa.ecore#//AbstractFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSequenceMessageValuations"
        upperBound="-1" eType="#//SequenceMessageValuation" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="capellacore.ecore#//Namespace behavior.ecore#//AbstractBehavior">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//ScenarioKind"
        defaultValueLiteral="UNSET"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="merged" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="preCondition" eType="ecore:EClass capellacore.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" eType="ecore:EClass capellacore.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedMessages" upperBound="-1"
        eType="#//SequenceMessage" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedFunctions" upperBound="-1"
        eType="ecore:EClass fa.ecore#//AbstractFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedParts" upperBound="-1"
        eType="ecore:EClass cs.ecore#//Part"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedScenarios" upperBound="-1"
        eType="#//Scenario"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedScenarios" upperBound="-1"
        eType="#//Scenario"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractCapability" abstract="true"
      eSuperTypes="capellacore.ecore#//Structure fa.ecore#//AbstractFunctionalChainContainer capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="preCondition" eType="ecore:EClass capellacore.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="postCondition" eType="ecore:EClass capellacore.ecore#//Constraint"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedScenarios" upperBound="-1"
        eType="#//Scenario" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="super" upperBound="-1"
        eType="#//AbstractCapability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="includedAbstractCapabilities"
        upperBound="-1" eType="#//AbstractCapability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="extendedAbstractCapabilities"
        upperBound="-1" eType="#//AbstractCapability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableInStates" upperBound="-1"
        eType="ecore:EClass capellacommon.ecore#//State"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedAbstractFunctions"
        upperBound="-1" eType="ecore:EClass fa.ecore#//AbstractFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedFunctionalChains"
        upperBound="-1" eType="ecore:EClass fa.ecore#//FunctionalChain"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CombinedFragment" eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//InteractionOperatorKind"
        defaultValueLiteral="UNSET"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InteractionOperand" eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="guard" eType="ecore:EClass capellacore.ecore#//Constraint"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SequenceMessageValuation" eSuperTypes="capellacore.ecore#//CapellaElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="exchangeItemElement" eType="ecore:EClass information.ecore#//ExchangeItemElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" eType="ecore:EClass modellingcore.ecore#//ValueSpecification"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="MessageKind">
    <eLiterals name="UNSET"/>
    <eLiterals name="ASYNCHRONOUS_CALL" value="1"/>
    <eLiterals name="SYNCHRONOUS_CALL" value="2"/>
    <eLiterals name="REPLY" value="3"/>
    <eLiterals name="DELETE" value="4"/>
    <eLiterals name="CREATE" value="5"/>
    <eLiterals name="TIMER" value="6"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScenarioKind">
    <eLiterals name="UNSET" value="4"/>
    <eLiterals name="INTERFACE"/>
    <eLiterals name="DATA_FLOW" value="1"/>
    <eLiterals name="INTERACTION" value="2"/>
    <eLiterals name="FUNCTIONAL" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="InteractionOperatorKind">
    <eLiterals name="UNSET" value="11"/>
    <eLiterals name="ALT"/>
    <eLiterals name="OPT" value="1"/>
    <eLiterals name="PAR" value="2"/>
    <eLiterals name="LOOP" value="3"/>
    <eLiterals name="CRITICAL" value="4"/>
    <eLiterals name="NEG" value="5"/>
    <eLiterals name="ASSERT" value="6"/>
    <eLiterals name="STRICT" value="7"/>
    <eLiterals name="SEQ" value="8"/>
    <eLiterals name="IGNORE" value="9"/>
    <eLiterals name="CONSIDER" value="10"/>
  </eClassifiers>
</ecore:EPackage>
