<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="la" nsURI="http://www.polarsys.org/capella/core/la/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.la">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/la/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalArchitecture" eSuperTypes="cs.ecore#//BlockArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalContext" eType="#//LogicalContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalComponent"
        eType="#//LogicalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalComponentPkg"
        eType="#//LogicalComponentPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalActorPkg" eType="#//LogicalActorPkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedCapabilityRealizationPkg"
        eType="#//CapabilityRealizationPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedLogicalFunctionPkg"
        eType="#//LogicalFunctionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedSystemAnalyses"
        upperBound="-1" eType="ecore:EClass ctx.ecore#//SystemAnalysis"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalFunction" eSuperTypes="fa.ecore#//AbstractFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalFunctionPkgs"
        upperBound="-1" eType="#//LogicalFunctionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedSystemFunctions"
        upperBound="-1" eType="ecore:EClass ctx.ecore#//SystemFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedLogicalFunctions"
        upperBound="-1" eType="#//LogicalFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalFunctionPkg" eSuperTypes="fa.ecore#//FunctionPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalFunctions"
        upperBound="-1" eType="#//LogicalFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalFunctionPkgs"
        upperBound="-1" eType="#//LogicalFunctionPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComponent" eSuperTypes="cs.ecore#//SystemComponent">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalComponents"
        upperBound="-1" eType="#//LogicalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalComponentPkgs"
        upperBound="-1" eType="#//LogicalComponentPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedLogicalFunctions"
        upperBound="-1" eType="#//LogicalFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedSystems" upperBound="-1"
        eType="ecore:EClass ctx.ecore#//System"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalComponentPkg" eSuperTypes="fa.ecore#//AbstractFunctionalStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalComponents"
        upperBound="-1" eType="#//LogicalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalComponentPkgs"
        upperBound="-1" eType="#//LogicalComponentPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityRealization" eSuperTypes="interaction.ecore#//AbstractCapability">
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingActors" upperBound="-1"
        eType="ecore:EClass cs.ecore#//AbstractActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="participatingSystemComponents"
        upperBound="-1" eType="ecore:EClass cs.ecore#//SystemComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedCapabilities" upperBound="-1"
        eType="ecore:EClass ctx.ecore#//Capability"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedCapabilityRealizations"
        upperBound="-1" eType="#//CapabilityRealization"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CapabilityRealizationPkg" eSuperTypes="capellacommon.ecore#//AbstractCapabilityPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCapabilityRealizations"
        upperBound="-1" eType="#//CapabilityRealization" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCapabilityRealizationPkgs"
        upperBound="-1" eType="#//CapabilityRealizationPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalActorPkg" eSuperTypes="fa.ecore#//AbstractFunctionalStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalActorPkgs"
        upperBound="-1" eType="#//LogicalActorPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedLogicalActors" upperBound="-1"
        eType="#//LogicalActor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalActor" eSuperTypes="cs.ecore#//AbstractActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedLogicalFunctions"
        upperBound="-1" eType="#//LogicalFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedSystemActors" upperBound="-1"
        eType="ecore:EClass ctx.ecore#//Actor"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LogicalContext" eSuperTypes="cs.ecore#//Component"/>
</ecore:EPackage>
