<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="modellingcore" nsURI="http://www.polarsys.org/capella/common/core/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.common.data.core">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/common/core/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ModelElement" abstract="true" eSuperTypes="emde.ecore#//ExtensibleElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sid" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConstraints" upperBound="-1"
        eType="#//AbstractConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractNamedElement" abstract="true"
      eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InformationsExchanger" abstract="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="TraceableElement" abstract="true" interface="true"
      eSuperTypes="#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractType" abstract="true" eSuperTypes="#//AbstractNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractConstraint" abstract="true"
      interface="true" eSuperTypes="#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedElements" upperBound="-1"
        eType="#//ModelElement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedSpecification" eType="#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ValueSpecification" abstract="true"
      interface="true" eSuperTypes="#//AbstractNamedElement"/>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractParameter" abstract="true" eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isException" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStream" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isOptional" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kindOfRate" eType="#//RateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="effect" eType="#//ParameterEffectKind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rate" eType="#//ValueSpecification"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="probability" eType="#//ValueSpecification"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractInformationFlow" abstract="true"
      eSuperTypes="#//AbstractNamedElement #//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="convoyedInformations" upperBound="-1"
        eType="#//AbstractExchangeItem"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractExchangeItem" abstract="true"
      eSuperTypes="#//AbstractType"/>
  <eClassifiers xsi:type="ecore:EClass" name="IState" abstract="true" interface="true"
      eSuperTypes="#//AbstractNamedElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="referencedStates" upperBound="-1"
        eType="#//IState"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="availableInStates" upperBound="-1"
        eType="#//IState"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ParameterEffectKind">
    <eLiterals name="create" value="2"/>
    <eLiterals name="read"/>
    <eLiterals name="update" value="1"/>
    <eLiterals name="delete" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="RateKind">
    <eLiterals name="Unspecified"/>
    <eLiterals name="Continuous" value="1"/>
    <eLiterals name="Discrete" value="2"/>
  </eClassifiers>
</ecore:EPackage>
