<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="oa" nsURI="http://www.polarsys.org/capella/core/oa/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.oa">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/oa/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalAnalysis" eSuperTypes="cs.ecore#//BlockArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperationalContext"
        eType="#//OperationalContext" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRolePkg" eType="#//RolePkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEntityPkg" eType="#//EntityPkg"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedOperationalCapabilityPkg"
        eType="#//OperationalCapabilityPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedOperationalActivityPkg"
        eType="#//OperationalActivityPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalScenario" abstract="true"
      eSuperTypes="capellacore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="context" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="objective" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalActivityPkg" eSuperTypes="fa.ecore#//FunctionPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperationalActivities"
        upperBound="-1" eType="#//OperationalActivity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperationalActivityPkgs"
        upperBound="-1" eType="#//OperationalActivityPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalActivity" eSuperTypes="fa.ecore#//AbstractFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperationalActivityPkgs"
        upperBound="-1" eType="#//OperationalActivityPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedOperationalActivities"
        upperBound="-1" eType="#//OperationalActivity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalProcess" eSuperTypes="fa.ecore#//FunctionalChain"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalCapabilityPkg" eSuperTypes="capellacommon.ecore#//AbstractCapabilityPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperationalCapabilities"
        upperBound="-1" eType="#//OperationalCapability" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedOperationalCapabilityPkgs"
        upperBound="-1" eType="#//OperationalCapabilityPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalCapability" eSuperTypes="interaction.ecore#//AbstractCapability capellacore.ecore#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EReference" name="involvedEntities" upperBound="-1"
        eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RolePkg" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRolePkgs" upperBound="-1"
        eType="#//RolePkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRoles" upperBound="-1"
        eType="#//Role" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Role" eSuperTypes="information.ecore#//Property">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedOperationalActivities"
        upperBound="-1" eType="#//OperationalActivity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EntityPkg" eSuperTypes="capellacore.ecore#//Structure fa.ecore#//AbstractFunctionalStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEntityPkgs" upperBound="-1"
        eType="#//EntityPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEntities" upperBound="-1"
        eType="#//Entity" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Entity" eSuperTypes="modellingcore.ecore#//InformationsExchanger capellacore.ecore#//InvolvedElement cs.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedEntities" upperBound="-1"
        eType="#//Entity" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedCommunicationMeans"
        upperBound="-1" eType="#//CommunicationMean" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedOperationalActivities"
        upperBound="-1" eType="#//OperationalActivity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedRoles" upperBound="-1"
        eType="#//Role"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalActor" eSuperTypes="#//Entity"/>
  <eClassifiers xsi:type="ecore:EClass" name="Location" eSuperTypes="cs.ecore#//Component">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="locationDescription" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CommunicationMean" eSuperTypes="fa.ecore#//ComponentExchange capellacore.ecore#//NamedElement capellacore.ecore#//CapellaElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceEntity" eType="#//Entity"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetEntity" eType="#//Entity"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OperationalContext" eSuperTypes="cs.ecore#//Component"/>
</ecore:EPackage>
