<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pa" nsURI="http://www.polarsys.org/capella/core/pa/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.pa">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/pa/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalArchitecture" eSuperTypes="cs.ecore#//BlockArchitecture">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalContext" eType="#//PhysicalContext"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponent"
        eType="#//PhysicalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponentPkg"
        eType="#//PhysicalComponentPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalActorPkg"
        eType="#//PhysicalActorPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedCapabilityRealizationPkg"
        eType="ecore:EClass la.ecore#//CapabilityRealizationPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPhysicalFunctionPkg"
        eType="#//PhysicalFunctionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeployments" upperBound="-1"
        eType="ecore:EClass cs.ecore#//AbstractDeploymentLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedLogicalArchitectures"
        upperBound="-1" eType="ecore:EClass la.ecore#//LogicalArchitecture"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalFunction" eSuperTypes="fa.ecore#//AbstractFunction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalFunctionPkgs"
        upperBound="-1" eType="#//PhysicalFunctionPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedLogicalFunctions"
        upperBound="-1" eType="ecore:EClass la.ecore#//LogicalFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalFunctionPkg" eSuperTypes="fa.ecore#//FunctionPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalFunctionPkgs"
        upperBound="-1" eType="#//PhysicalFunctionPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalComponent" abstract="true"
      eSuperTypes="cs.ecore#//SystemComponent cs.ecore#//DeployableElement cs.ecore#//DeploymentTarget">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//PhysicalComponentKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nature" eType="#//PhysicalComponentNature"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentLinks" upperBound="-1"
        eType="ecore:EClass cs.ecore#//AbstractDeploymentLink" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentAspect"
        eType="#//deployment/DeploymentAspect" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalComponent" eSuperTypes="#//AbstractPhysicalComponent cs.ecore#//AbstractPhysicalArtifact">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponentPkgs"
        upperBound="-1" eType="#//PhysicalComponentPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedLogicalComponents"
        ordered="false" upperBound="-1" eType="ecore:EClass la.ecore#//LogicalComponent"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalActorPkg" eSuperTypes="fa.ecore#//AbstractFunctionalStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalActorPkgs"
        upperBound="-1" eType="#//PhysicalActorPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalActors" upperBound="-1"
        eType="#//PhysicalActor" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalComponentPkg" eSuperTypes="fa.ecore#//AbstractFunctionalStructure information.ecore#//AssociationPkg">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedComponents" upperBound="-1"
        eType="#//PhysicalComponent" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalComponentPkgs"
        upperBound="-1" eType="#//PhysicalComponentPkg" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedKeyParts" upperBound="-1"
        eType="ecore:EClass information.ecore#//KeyPart" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalActor" eSuperTypes="#//AbstractPhysicalComponent cs.ecore#//AbstractActor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="allocatedPhysicalFunctions"
        upperBound="-1" eType="#//PhysicalFunction"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="realizedLogicalActors"
        upperBound="-1" eType="ecore:EClass la.ecore#//LogicalActor"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deployedPhysicalComponents"
        upperBound="-1" eType="#//PhysicalComponent"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalNode" eSuperTypes="#//PhysicalComponent"/>
  <eClassifiers xsi:type="ecore:EClass" name="PhysicalContext" eSuperTypes="cs.ecore#//Component"/>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalComponentKind">
    <eLiterals name="UNSET"/>
    <eLiterals name="HARDWARE" value="1"/>
    <eLiterals name="HARDWARE_COMPUTER" value="2"/>
    <eLiterals name="SOFTWARE" value="3"/>
    <eLiterals name="SOFTWARE_DEPLOYMENT_UNIT" value="4"/>
    <eLiterals name="SOFTWARE_EXECUTION_UNIT" value="5"/>
    <eLiterals name="SOFTWARE_APPLICATION" value="6"/>
    <eLiterals name="FIRMWARE" value="7"/>
    <eLiterals name="PERSON" value="8"/>
    <eLiterals name="FACILITIES" value="9"/>
    <eLiterals name="DATA" value="10"/>
    <eLiterals name="MATERIALS" value="11"/>
    <eLiterals name="SERVICES" value="12"/>
    <eLiterals name="PROCESSES" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PhysicalComponentNature">
    <eLiterals name="UNSET"/>
    <eLiterals name="BEHAVIOR" value="1"/>
    <eLiterals name="NODE" value="2"/>
  </eClassifiers>
  <eSubpackages name="deployment" nsURI="http://www.polarsys.org/capella/core/pa/deployment/0.8.0/semantic"
      nsPrefix="org.polarsys.capella.core.data.pa.deployment">
    <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
      <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/pa/deployment/0.8.0"/>
    </eAnnotations>
    <eClassifiers xsi:type="ecore:EClass" name="ComponentInstance" eSuperTypes="#//deployment/AbstractPhysicalInstance cs.ecore#//DeployableElement cs.ecore#//DeploymentTarget">
      <eStructuralFeatures xsi:type="ecore:EReference" name="portInstances" upperBound="-1"
          eType="#//deployment/PortInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedAbstractPhysicalInstances"
          upperBound="-1" eType="#//deployment/AbstractPhysicalInstance" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedInstanceDeploymentLinks"
          upperBound="-1" eType="#//deployment/InstanceDeploymentLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//AbstractPhysicalComponent"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ConnectionInstance" eSuperTypes="#//deployment/AbstractPhysicalInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass fa.ecore#//ComponentExchange"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentAspect" eSuperTypes="capellacore.ecore#//Structure">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedConfigurations"
          upperBound="-1" eType="#//deployment/DeploymentConfiguration" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentAspects"
          upperBound="-1" eType="#//deployment/DeploymentAspect" containment="true"
          resolveProxies="false"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="DeploymentConfiguration" eSuperTypes="capellacore.ecore#//NamedElement">
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedDeploymentLinks"
          upperBound="-1" eType="ecore:EClass cs.ecore#//AbstractDeploymentLink" containment="true"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="ownedPhysicalInstances"
          upperBound="-1" eType="#//deployment/AbstractPhysicalInstance" containment="true"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="InstanceDeploymentLink" eSuperTypes="cs.ecore#//AbstractDeploymentLink"/>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractPhysicalInstance" abstract="true"
        eSuperTypes="capellacore.ecore#//CapellaElement"/>
    <eClassifiers xsi:type="ecore:EClass" name="PortInstance" eSuperTypes="#//deployment/AbstractPhysicalInstance">
      <eStructuralFeatures xsi:type="ecore:EReference" name="connections" upperBound="-1"
          eType="#//deployment/ConnectionInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="component" lowerBound="1"
          eType="#//deployment/ComponentInstance"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="ecore:EClass fa.ecore#//ComponentPort"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
