<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="requirement" nsURI="http://www.polarsys.org/capella/core/requirement/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.requirement">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/requirement/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsPkg" eSuperTypes="capellacore.ecore#//Structure">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalInformation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="level" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRequirements" upperBound="-1"
        eType="#//Requirement" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ownedRequirementPkgs" upperBound="-1"
        eType="#//RequirementsPkg" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RequirementsTrace" eSuperTypes="capellacore.ecore#//CapellaElement modellingcore.ecore#//TraceableElement modellingcore.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="source" lowerBound="1"
        eType="ecore:EClass modellingcore.ecore#//TraceableElement" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" lowerBound="1"
        eType="ecore:EClass modellingcore.ecore#//TraceableElement" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Requirement" abstract="true" eSuperTypes="capellacore.ecore#//Namespace">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isObsolete" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requirementId" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="additionalInformation"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verificationMethod" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="verificationPhase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="implementationVersion"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="feature" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="relatedCapellaElements"
        upperBound="-1" eType="ecore:EClass capellacore.ecore#//CapellaElement"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SystemFunctionalInterfaceRequirement"
      eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemFunctionalRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemNonFunctionalInterfaceRequirement"
      eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemNonFunctionalRequirement" eSuperTypes="#//Requirement"/>
  <eClassifiers xsi:type="ecore:EClass" name="SystemUserRequirement" eSuperTypes="#//Requirement"/>
</ecore:EPackage>
