<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sharedmodel" nsURI="http://www.polarsys.org/capella/core/sharedmodel/0.8.0/semantic"
    nsPrefix="org.polarsys.capella.core.data.sharedmodel">
  <eAnnotations source="http://www.polarsys.org/capella/xmlpivot">
    <details key="sourceNsURI" value="http://www.polarsys.org/capella/core/sharedmodel/0.8.0"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SharedPkg" eSuperTypes="capellamodeller.ecore#//ModelRoot capellacore.ecore#//Structure"/>
</ecore:EPackage>
