<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="perfo" nsURI="http://www.polarsys.org/capella/perfo" nsPrefix="perfo">
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceCriteria" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minValue" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceConsumption" eSuperTypes="#//PerformanceCriteria"/>
  <eClassifiers xsi:type="ecore:EClass" name="PerformanceCapacity" eSuperTypes="#//PerformanceCriteria"/>
  <eClassifiers xsi:type="ecore:EClass" name="TimeConsumption" eSuperTypes="#//PerformanceConsumption #//UnityElement platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value=" http://www.polarsys.org/capella/core/fa/1.0.0#//FunctionalExchange http://www.polarsys.org/capella/core/pa/1.0.0#//PhysicalFunction http://www.polarsys.org/capella/core/la/1.0.0#//LogicalFunction"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraintMapping">
      <details key="Mapping" value=" platform:/plugin/org.polarsys.capella.core.data.gen/model/FunctionalAnalysis.ecore#//FunctionalExchange platform:/plugin/org.polarsys.capella.core.data.gen/model/PhysicalArchitecture.ecore#//PhysicalFunction platform:/plugin/org.polarsys.capella.core.data.gen/model/LogicalArchitecture.ecore#//LogicalFunction"/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TimeCapacity" eSuperTypes="#//PerformanceCapacity #//UnityElement platform:/plugin/org.polarsys.kitalpha.emde/model/eMDE.ecore#//ElementExtension">
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraint">
      <details key="ExtendedElement" value=" http://www.polarsys.org/capella/core/fa/1.0.0#//FunctionalChain"/>
    </eAnnotations>
    <eAnnotations source="http://www.polarsys.org/kitalpha/emde/1.0.0/constraintMapping">
      <details key="Mapping" value=" platform:/plugin/org.polarsys.capella.core.data.gen/model/FunctionalAnalysis.ecore#//FunctionalChain"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentExecutionTime" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="UnityElement" eSuperTypes="platform:/plugin/org.polarsys.capella.core.data.gen/model/CapellaCore.ecore#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="measurementUnit" eType="#//measurementUnit_Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="measurementUnit_Type">
    <eLiterals name="Millisecond" literal="Millisecond"/>
  </eClassifiers>
</ecore:EPackage>
